local nldecl = require 'nelua.plugins.nldecl'
local fs = require 'nelua.utils.fs'

local function appendAll(dest, src)
   table.move(src, 1, #src, #dest + 1, dest)
end

if ccinfo.is_tcc then
   if ccinfo.is_windows then
      cflags "-D_WIN32_WINNT_VISTA"
      cflags "-DMAPVK_VSC_TO_VK"
      cflags "-DMAPVK_VK_TO_VSC"
      cflags "-D_WIN32_WINNT_WIN7"
   end
   cincdir "vendor/glfw/deps"
   cincdir "vendor/glfw/deps/mingw"
   cinclude "math.h"
end

-- Configure emscripten flags
--------------------------------------------------
if ccinfo.is_emscripten then
   -- emscripten had WebGL2 as GLES3 headers/symbols
   -- so no need to include the vendor headers
   cinclude "GLES3/gl3.h"
   cdefine "NANOVG_GLES3_IMPLEMENTATION"
else
   cincdir "vendor/nanovg/glad/include"
   cinclude "glad/glad.h"
   cfile "vendor/nanovg/glad/src/glad.c"
   -- no need for Generate Bindings for glad becuase nanovg_gl.h depend on it
   -- so it will automatically generated by nldecl
   cdefine "NANOVG_GL3_IMPLEMENTATION"
end
--------------------------------------------------

-- Compiling NanoVG
--------------------------------------------------
linklib "m"
cdefine "_CRT_SECURE_NO_WARNINGS"

cfile "vendor/nanovg/src/nanovg.c"
cincdir "vendor/nanovg/src"
cinclude "nanovg.h"
cinclude "nanovg_gl.h"
-- nanovg_gl_utils.h hardcodes a glad.h include, so it cant be used for the web build
if not ccinfo.is_emscripten then
   cinclude "nanovg_gl_utils.h"
end

if ccinfo.is_emscripten then
   if not fs.isfile('vendor/nanovg_web/init.nelua') then
      nldecl.generate_bindings_file {
         cc = 'emcc',
         defines = { 'NANOVG_GLES3_IMPLEMENTATION' },
         include_dirs = { 'vendor/nanovg/src' },
         output_file = 'vendor/nanovg_web/init.nelua',
         -- GLES3/gl3.h for opengl primitive types
         parse_includes = {'GLES3/gl3.h', 'nanovg.h', 'nanovg_gl.h' },
      }
   end
else
   if not fs.isfile('vendor/nanovg/init.nelua') then
      nldecl.generate_bindings_file {
         include_dirs = { 'vendor/nanovg/src', 'vendor/nanovg/glad/include' },
         output_file = 'vendor/nanovg/init.nelua',
         parse_includes = {'nanovg.h', 'nanovg_gl.h', 'nanovg_gl_utils.h' },
      }
   end
end
--------------------------------------------------

-- Compiling GLFW
-- the same emscripten thing apply as well
--------------------------------------------------
if ccinfo.is_emscripten then
   cflags "-sUSE_GLFW=3"
   cflags "-sUSE_WEBGL2=1"
   cflags "-sMAX_WEBGL_VERSION=2"
   cflags "-sALLOW_MEMORY_GROWTH=1"
   cflags "--preload-file assets"
   cflags "--shell-file web/shell.html"
   cinclude "GLFW/glfw3.h"
else

cincdir "vendor/glfw/src"
cincdir "vendor/glfw/include"
cinclude "GLFW/glfw3.h"

local sources = {
   "vendor/glfw/src/context.c",
   "vendor/glfw/src/egl_context.c",
   "vendor/glfw/src/init.c",
   "vendor/glfw/src/input.c",
   "vendor/glfw/src/monitor.c",
   "vendor/glfw/src/null_init.c",
   "vendor/glfw/src/null_joystick.c",
   "vendor/glfw/src/null_monitor.c",
   "vendor/glfw/src/null_window.c",
   "vendor/glfw/src/osmesa_context.c",
   "vendor/glfw/src/platform.c",
   "vendor/glfw/src/vulkan.c",
   "vendor/glfw/src/window.c",
}

local windows_sources = {
   "vendor/glfw/src/wgl_context.c",
   "vendor/glfw/src/win32_init.c",
   "vendor/glfw/src/win32_joystick.c",
   "vendor/glfw/src/win32_module.c",
   "vendor/glfw/src/win32_monitor.c",
   "vendor/glfw/src/win32_thread.c",
   "vendor/glfw/src/win32_time.c",
   "vendor/glfw/src/win32_window.c",
}

local linux_sources = {
    "vendor/glfw/src/linux_joystick.c",
    "vendor/glfw/src/posix_module.c",
    "vendor/glfw/src/posix_poll.c",
    "vendor/glfw/src/posix_thread.c",
    "vendor/glfw/src/posix_time.c",
    "vendor/glfw/src/xkb_unicode.c",
}

local linux_x11_sources = {
    "vendor/glfw/src/glx_context.c",
    "vendor/glfw/src/x11_init.c",
    "vendor/glfw/src/x11_monitor.c",
    "vendor/glfw/src/x11_window.c",
}

local linux_wl_sources = {
    "vendor/glfw/src/wl_init.c",
    "vendor/glfw/src/wl_monitor.c",
    "vendor/glfw/src/wl_window.c",
}

-- Generate Wayland Headers
function generate_wayland_protocol(protocol_file)
   local protocol_path = "vendor/glfw/deps/wayland/" .. protocol_file
   local out_dir = "vendor/wayland-headers/"
   local header_file = out_dir .. string.gsub(protocol_file, "%.xml$", "-client-protocol.h")
   local code_file = out_dir .. string.gsub(protocol_file, "%.xml$", "-client-protocol-code.h")
   if not fs.isfile(header_file) then
      local client_command = string.format("wayland-scanner client-header \"%s\" \"%s\"",
					   protocol_path,
					   header_file)
      os.execute(client_command)
   end
   if not fs.isfile(code_file) then
      local code_command = string.format("wayland-scanner private-code \"%s\" \"%s\"",
					 protocol_path,
					 code_file)
      os.execute(code_command)
   end
end

if ccinfo.is_linux then
   appendAll(sources, linux_sources)

   appendAll(sources, linux_x11_sources)
   cflags "-D_GLFW_X11"
   cincdir "vendor/x11-headers"

   appendAll(sources, linux_wl_sources)
   cflags "-D_GLFW_WAYLAND"
   cflags "-Wno-implicit-function-declaration"
   cflags "-Ivendor/wayland-headers"
   generate_wayland_protocol("wayland.xml")
   generate_wayland_protocol("viewporter.xml")
   generate_wayland_protocol("xdg-shell.xml")
   generate_wayland_protocol("idle-inhibit-unstable-v1.xml")
   generate_wayland_protocol("pointer-constraints-unstable-v1.xml")
   generate_wayland_protocol("relative-pointer-unstable-v1.xml")
   generate_wayland_protocol("fractional-scale-v1.xml")
   generate_wayland_protocol("xdg-activation-v1.xml")
   generate_wayland_protocol("xdg-decoration-unstable-v1.xml")
end

if ccinfo.is_windows then
   appendAll(sources, windows_sources)
   cflags "-D_GLFW_WIN32"
   linklib "gdi32"
   linklib "opengl32"
   linklib "shell32"
   linklib "user32"
end

for _, src in ipairs(sources) do
   cfile(src)
end

end -- not ccinfo.is_emscripten

-- Generate Bindings for GLFW
if not fs.isfile('vendor/glfw/init.nelua') then
   nldecl.generate_bindings_file {
      include_dirs = { 'vendor/glfw/include' },
      output_file = 'vendor/glfw/init.nelua',
      parse_includes = {'GLFW/glfw3.h'},
   }
end
--------------------------------------------------
