##[[
function rPrint(table, indent, depth)
    -- Default parameters
    indent = indent or ""
    depth = depth or 2
    
    -- Check if max depth reached
    if depth <= 0 then
        print(indent .. "[Max depth reached]")
        return
    end
    
    -- Iterate through all keys in the table
    for key, value in pairs(table) do
        -- Handle different types of values
        if type(value) == "table" then
            -- If value is another table, print the key and recursively print its contents
            print(indent .. tostring(key) .. " (table):")
            rPrint(value, indent .. "  ", depth - 1)
        else
            -- Print primitive values directly
            print(indent .. tostring(key) .. ": " .. tostring(value))
        end
    end
end
]]

local function_concept: type = #[concept(function(x) return x.type.is_function end)]#
   
global function rk4_step(f: function_concept, t: float64, h: float64, y: auto): float64
   ## local argnum = select("#", ...)
   ## static_assert(argnum == #f.type.argattrs - 1, "expected that function args is the same for ODE solver")
   ##[[
     local k2 = {}
     local k3 = {}
     local k4 = {}
     for i=1,argnum do
        local arg = select(i, ...)
        local mul_op = aster.BinaryOp {aster.Number {"0.5"}, "mul", aster.Id {"h"} }
        local mul_op_1 = aster.BinaryOp { mul_op, "mul", aster.Id {"k1"} }
        local mul_op_2 = aster.BinaryOp { mul_op, "mul", aster.Id {"k2"} }
        k2[i] = aster.BinaryOp { arg, 'add', mul_op_1 }
        k3[i] = aster.BinaryOp { arg, 'add', mul_op_2 }
        k4[i] = aster.BinaryOp { arg, 'add', aster.BinaryOp { aster.Id {"h"}, "mul", aster.Id {"k3"} } }
     end
   ]]

   local y = #[select(1, ...)]#
   local k1 = f(t, ...)
   local k2 = f(t + 0.5 * h, #[aster.unpack(k2)]#)
   local k3 = f(t + 0.5 * h, #[aster.unpack(k3)]#)
   local k4 = f(t + h, #[aster.unpack(k4)]#)

   return y + h * (k1 + 2*k2 + 2*k3 + k4) / 6
end

require "span"

local vec: type = @span(integer)

function vec:len(): usize
   return self.size
end

local base = (@[4]integer) {1, 2, 3, 4}

local a: vec = &base
local b: span(int32) = &base

print(a:len())
print(b:len())
