## pragma{nogc=true}
## require "./build.lua"

## function default_values(r, values)
   ## local t = r.name
   ## local fields = r.value.fields

   function #|t|#.new(v: #|t|#): #|t|# <inline>
      local res: #|t|#
      ## for _, f in ipairs(fields) do
	 ## for name, value in pairs(values) do
	    ## if f.name == name then
	       res.#|name|# = v.#|name|# == 0 and #[value]# or v.#|name|#
	       ## goto continue
	    ## end
         ## end
	 res.#|f.name|# = v.#|f.name|#
	 ## ::continue::
      ## end
      return res
   end
## end

## function unpack_fields(value)
   ## local t = value.type
   ## for _, field in ipairs(t.fields) do
      local #|field.name|# = #|value.name|#.#|field.name|#
   ## end
## end

require "glad"
require "glfw"
require "nanovg"

require "pendulum"
require "spring"

local function errorcb(error: cint, desc: cstring)
   print("GLFW error", error, string(desc))
end

local function key(window: *GLFWwindow, key: cint, scancode: cint, action: cint, mods: cint)
   if key == GLFW_KEY_ESCAPE and action == GLFW_RELEASE then
      glfwSetWindowShouldClose(window, GL_TRUE)
   end
end

if glfwInit() == 0 then
   print("failed to init GLFW")
   return -1
end

glfwSetErrorCallback(errorcb)
glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3)
glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 2)
glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE)
glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE)

local window = glfwCreateWindow(1000, 600, "NanoVG")
defer glfwTerminate() end

if not window then
   print("Could not initialze GLFW window")
   return -1
end

glfwSetKeyCallback(window, key)
glfwMakeContextCurrent(window)

if gladLoadGLLoader((@GLADloadproc)(glfwGetProcAddress)) == 0 then
   print("could not init glad")
   return -1
end

local vg = nvgCreateGL3(NVG_STENCIL_STROKES | NVG_DEBUG | NVG_ANTIALIAS)
defer nvgDeleteGL3(vg) end

if vg == nilptr then
   print("Could not init nanovg")
   return -1
end

local winWidth: cint, winHeight: cint
local fbWidth: cint, fbHeight: cint
glfwGetWindowSize(window, &winWidth, &winHeight)
glfwGetFramebufferSize(window, &fbWidth, &fbHeight)

local pxRatio = fbWidth / winWidth
local fb = nvgluCreateFramebuffer(vg, 100*pxRatio,100*pxRatio, NVG_IMAGE_REPEATX | NVG_IMAGE_REPEATY)
if fb == nilptr then
   print("Could not create FBO.")
   return -1
end
defer nvgluDeleteFramebuffer(fb) end

glfwSwapInterval(1)
glfwSetTime(0)

local winWidth: cint, winHeight: cint
local prev = glfwGetTime()

while glfwWindowShouldClose(window) == 0 do
   local t = glfwGetTime()
   local dt = t - prev
   prev = t

   glfwGetWindowSize(window, &winWidth, &winHeight)
   glfwGetFramebufferSize(window, &fbWidth, &fbHeight)

   pxRatio = fbWidth / winWidth
   glViewport(0, 0, fbWidth, fbHeight)
   glClearColor(0.92, 0.92, 0.94, 1.0)
   glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT | GL_STENCIL_BUFFER_BIT)

   nvgBeginFrame(vg, winWidth, winHeight, pxRatio)
   defer
     nvgEndFrame(vg)
     glfwSwapBuffers(window)
     glfwPollEvents()
   end

   -- draw_pendulum_simulation(vg, t, dt, winWidth)
   draw_spring_simulation(vg, t, dt, winWidth, winHeight)
end
