## pragma{nogc=true}

require "eq_system"

local function_concept: type = #[concept(function(x)
  if x.type.is_function then return true end
  return false, "param must be a function type"
end)]#

-- Range-Kutta method for solving first order ODE with single or multiple variables
-- y argument can be a scalar or an vector of scalars
global function rk4_step(f: function_concept, t: float64, h: float64, y: auto): auto
   ## local f_ret = f.type.rettypes[1]
   ## if y.type.is_container then
      ## static_assert(y.type.is_container and f_ret.is_container)
      ## static_assert(y.type.subtype.is_scalar and f_ret.subtype.is_scalar)
   ## else
      ## static_assert(y.type.is_scalar and f_ret.is_scalar)
   ## end

   local k1 = MulSystem(h, f(t,y))
   local k2 = MulSystem(h, f(t + 0.5*h, SumSystem(y, MulSystem(0.5, k1))))
   local k3 = MulSystem(h, f(t + 0.5*h, SumSystem(y, MulSystem(0.5, k2))))
   local k4 = MulSystem(h, f(t + h, SumSystem(y, k3)))
   local res = SumSystem(y, DivSystem( SumSystem(k1, MulSystem(2.0, k2), MulSystem(2.0, k3), k4) , 6.0))

   return res
end

-- Same Range-Kutta method for solving second order ODE with single or multiple variables
-- y and dy arguments can be scalars or vectors of scalars
global function rk4_2_step(f: function_concept, t: float64, h: float64, y: auto, dy: auto): (auto, auto)
   ## static_assert(y.type == dy.type)

   ## local f_ret = f.type.rettypes[1]
   ## if y.type.is_container then
      ## static_assert(y.type.is_container and f_ret.is_container)
   ## else
      ## static_assert(y.type.is_scalar and f_ret.is_scalar)
   ## end

   local k1_1 = dy
   local k1_2 = f(t, y, dy)

   local k2_1 = SumSystem(dy, MulSystem(0.5*h, k1_2))
   local k2_2 = f(t + 0.5*h, SumSystem(y, MulSystem(0.5*h, k1_1)), SumSystem(dy, MulSystem(0.5*h, k1_2)))

   local k3_1 = SumSystem(dy, MulSystem(0.5*h, k2_2))
   local k3_2 = f(t + 0.5*h, SumSystem(y, MulSystem(0.5*h, k2_1)), SumSystem(dy, MulSystem(0.5*h, k2_2)))

   local k4_1 = SumSystem(dy, MulSystem(h, k3_2))
   local k4_2 = f(t + h, SumSystem(y, MulSystem(h, k3_1)), SumSystem(dy, MulSystem(h, k3_2)))

   return SumSystem(y, DivSystem(MulSystem(h, SumSystem(k1_1, MulSystem(2.0, k2_1), MulSystem(2.0, k3_1), k4_1)), 6.0)),
      SumSystem(dy, DivSystem(MulSystem(h, SumSystem(k1_2, MulSystem(2.0, k2_2), MulSystem(2.0, k3_2), k4_2)), 6.0))
end
