## pragma{nogc=true}
## require "./build.lua"

## function default_values(r, values)
   ## local t = r.name
   ## local fields = r.value.fields

   function #|t|#.new(v: #|t|#): #|t|# <inline>
      local res: #|t|#
      ## for _, f in ipairs(fields) do
	 ## for name, value in pairs(values) do
	    ## if f.name == name then
	       res.#|name|# = v.#|name|# == 0 and #[value]# or v.#|name|#
	       ## goto continue
	    ## end
         ## end
	 res.#|f.name|# = v.#|f.name|#
	 ## ::continue::
      ## end
      return res
   end
## end

## function unpack_fields(value)
   ## local t = value.type
   ## for _, field in ipairs(t.fields) do
      local #|field.name|# = #|value.name|#.#|field.name|#
   ## end
## end

-- Include Libraries
require "glad"
require "glfw"
require "nanovg"

-- Global variables
global cursor_x: float64, cursor_y: float64 -- cursor position
global window_w: cint, window_h: cint = 800, 600 -- window dimensions
global fb_w: cint, fb_h: cint = 800, 600 -- window dimensions

-- load other files
require "pendulum"
require "spring"
require "ui"

local function error_callback(error: cint, desc: cstring)
   print("GLFW error", error, string(desc))
end

local function key_callback(window: *GLFWwindow, key: cint, scancode: cint, action: cint, mods: cint)
   if key == GLFW_KEY_ESCAPE and action == GLFW_RELEASE then
      glfwSetWindowShouldClose(window, GL_TRUE)
   end
end

if glfwInit() == 0 then
   print("failed to init GLFW")
   return -1
end

glfwSetErrorCallback(error_callback)
glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3)
glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 2)
glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE)
glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE)

local window = glfwCreateWindow(1000, 600, "Simulation")
defer glfwTerminate() end

if not window then
   print("Could not initialze GLFW window")
   return -1
end

glfwMakeContextCurrent(window)

-- Enable VSYNC
glfwSwapInterval(1)

if gladLoadGLLoader((@GLADloadproc)(glfwGetProcAddress)) == 0 then
   print("could not init glad")
   return -1
end

local vg = nvgCreateGL3(NVG_STENCIL_STROKES | NVG_DEBUG | NVG_ANTIALIAS)
defer nvgDeleteGL3(vg) end

if vg == nilptr then
   print("Could not init nanovg")
   return -1
end

-- Keyboard Callback
glfwSetKeyCallback(window, key_callback)

local pxRatio = fb_w / window_w
local fb = nvgluCreateFramebuffer(vg, 100*pxRatio,100*pxRatio, NVG_IMAGE_REPEATX | NVG_IMAGE_REPEATY)
if fb == nilptr then
   print("Could not create FBO.")
   return -1
end
defer nvgluDeleteFramebuffer(fb) end

-- Set the time
glfwSetTime(0)
local prev = glfwGetTime()

while glfwWindowShouldClose(window) == 0 do
   -- Cursor Position
   glfwGetCursorPos(window, &cursor_x, &cursor_y)

   -- Window Size
   glfwGetWindowSize(window, &window_w, &window_h)
   glfwGetFramebufferSize(window, &fb_w, &fb_h)

   local t = glfwGetTime()
   local dt = t - prev
   prev = t

   pxRatio = fb_w / window_w
   glViewport(0, 0, fb_w, fb_h)
   glClearColor(.92, .92, .94, 1.0)
   glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT | GL_STENCIL_BUFFER_BIT)

   nvgBeginFrame(vg, window_w, window_h, pxRatio)

   defer
     nvgEndFrame(vg)
     glfwSwapBuffers(window)
     glfwPollEvents()
   end

   draw_pendulum_simulation(vg, t, dt)
   draw_spring_simulation(vg, t, dt, window_w, window_h)
   draw_double_pendulum_simulation(vg, t, dt, window_w)
   draw_double_spring_simulation(vg, t, dt, window_w, window_h)
   -- for idx=0,5 do
   --    local y = 50 + 40.0 * (idx+1) + idx * 100
   --    drawButton(vg, { 20, y, 200, 80 }, "btn_" .. tostring(idx+1))
   -- end
end
