require "common"
require "ode"
require "math"

global Spring = @record {
   position: Vec2,
   length: float32,
   rotation: float32
}

global Damper = @record {
   position: Vec2,
   length: float32,
   rotation: float32
}

global function drawSpring(vg: *NVGcontext, spring: Spring)
   ## unpack_fields(spring)

   nvgSave(vg)
   defer nvgRestore(vg) end

   -- Transformations
   nvgTranslate(vg, position.x, position.y)
   nvgRotate(vg, rotation)
   defer nvgResetTransform(vg) end

   -- Drawing
   nvgStrokeWidth(vg, 3.0)
   nvgStrokeColor(vg, nvgRGB(15, 15, 15))
   nvgLineCap(vg, NVG_ROUND)
   nvgBeginPath(vg)
   nvgMoveTo(vg, 0, 0)

   local pitch = 25

   for i=0,pitch do
      local h
      if i == 0 or i == pitch then
	 h = 0.0
      else
         h = (i % 2 == 0) and 5.0 or -5.0
      end
      nvgLineTo(vg, length / 8 + 6 * i * length / (8*pitch), h)
   end
   nvgLineTo(vg, length, 0)
   nvgStroke(vg)
end

global function drawDamper(vg: *NVGcontext, damper: Damper)
   ## unpack_fields(damper)

   local cr = 20.0 -- cylinder radius
   local cl = 30.0 -- cylinder length
   local pl = 15.0 -- piston length
   
   nvgSave(vg)
   defer nvgRestore(vg) end
   
   -- Transformations
   nvgTranslate(vg, position.x, position.y)
   nvgRotate(vg, rotation)
   defer nvgResetTransform(vg) end

   -- Drawing
   nvgStrokeWidth(vg, 3.0)
   nvgStrokeColor(vg, nvgRGB(0, 0, 0))
   nvgLineCap(vg, NVG_SQUARE)

   nvgBeginPath(vg)
   nvgMoveTo(vg, (length - pl) / 2, -cr/2)
   nvgLineTo(vg, (length + pl) / 2 - cl, -cr/2)
   nvgMoveTo(vg, (length - pl) / 2, cr/2)
   nvgLineTo(vg, (length + pl) / 2 - cl, cr/2)

   nvgMoveTo(vg, 0, 0)
   nvgLineTo(vg, (length - pl) / 2, 0)
   nvgRect(vg, (length - pl) / 2, -cr / 2, pl, cr)
   nvgMoveTo(vg, (length + pl) / 2, 0)
   nvgLineTo(vg, length, 0)
   nvgStroke(vg)
end

local L = 150.0
local dx = 100.0
local dv = 0.0
local mass = 10.0
local k = 3000.0
local b = 1.0

local function accel(t: float64, x: float64, dx: float64): float64
   return -(k/mass) * x - (b/mass) * dx
end

global function draw_spring_simulation(vg: *NVGcontext, t: float64, dt: float64, w: float64, h: float64)
   dx, dv = rk4_2_step(accel, t, dt, dx, dv)
   
   local damper = Damper {
      position = { w / 4 - 7.5, h / 2 - 10.0 },
      length = L + dx,
   }

   local spring = Spring {
      position = { w / 4 - 7.5, h / 2 + 30.0 },
      length = L + dx,
   }

   local h_ground = Ground.new {
      position = { w / 4 - 70.0, h / 2 },
      size = { 100.0, 30.0 },
      rotation = -math.pi / 2
   }

   local v_ground = Ground.new {
      position = { w / 4, h / 2 + 70.0 },
      size = { 500.0, 30.0 },
      rotation = math.pi
   }
   
   drawGround(vg, h_ground)
   drawGround(vg, v_ground)
   drawSpring(vg, spring)
   drawDamper(vg, damper)
   drawRect(vg, { w / 4 + dx + L - 7.5, h / 2 - 27.5, 100, 75 })

end

local m1 = 3.0
local m2 = 2.0
local k1 = 100.0
local k2 = 200.0
local b1 = 1.0
local b2 = 1.0
local L1 = 150.0
local L2 = 200.0
local w1 = 70.0

local x = (@[2]float64) { 50.0, 100.0 }
local dx: [2]float64

local function motion_system(t: float64, x: [2]float64, dx: [2]float64): [2]float64
   local x1 = x[0]
   local x2 = x[1]

   local dx1 = dx[0]
   local dx2 = dx[1]
   
   return {
      (k2/m1) * (x2 - x1) - (k1/m1) * x1 - (b2/m1)*(dx2 - dx1) - (b1/m1)*dx1,
      -(k2/m2) * (x2 - x1) - (b2/m2) * (dx2 - dx1)
   }
end

global function draw_double_spring_simulation(vg: *NVGcontext, t: float64, dt: float64, w: float64, h: float64)
   x, dx = rk4_2_step(motion_system, t, dt, x, dx)

   local x1 = x[0]
   local x2 = x[1]

   local damper_1 = Damper {
      position = { w / 4 - 7.5, h / 2 - 10.0 },
      length = L1 + x1,
   }

   local damper_2 = Damper {
      position = { w / 4 - 7.5 + L1 + x1 + w1, h / 2 - 10.0 },
      length = L2 + x2,
   }
   
   local spring_1 = Spring {
      position = { w / 4 - 7.5, h / 2 + 30.0 },
      length = L1 + x1,
   }

   local spring_2 = Spring {
      position = { w / 4 - 7.5 + L1 + x1 + w1, h / 2 + 30.0 },
      length = L2 + x2,
   }

   local h_ground = Ground.new {
      position = { w / 4 - 70.0, h / 2 },
      size = { 100.0, 30.0 },
      rotation = -math.pi / 2
   }

   local v_ground = Ground.new {
      position = { w / 4 - 5.0, h / 2 + 70.0 },
      size = { 600.0, 30.0 },
      rotation = math.pi
   }
   
   drawGround(vg, h_ground)
   drawGround(vg, v_ground)

   drawSpring(vg, spring_1)
   drawDamper(vg, damper_1)

   drawSpring(vg, spring_2)
   drawDamper(vg, damper_2)
   
   drawRect(vg, { w / 4 + x1 + L1 - 7.5, h / 2 - 27.5, w1, 75 })
   drawRect(vg, { w / 4 + x1 + L1 - 7.5 + w1 + L2 + x2, h / 2 - 27.5, w1, 75 })
end
